# ----------------------- #
#      Main Configs       #
# ----------------------- #
name: Your New Jekyll Site
description: 'A Jekyll theme'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
baseurl: /inuit-shelter
permalink: none
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false 

include: []
exclude: ['.gitignore', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'Rakefile', 'README.md', 'watch.sh', 'shelter.scss', 'inuit.css', 'sass', '.DS_Store']

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# prose.io template
prose:
  rooturl: '_posts'
  siteurl: 'http://nevvkid.github.io/inuit-shelter/'
  relativeLinks: 'http://nevvkid.github.io/inuit-shelter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "text"
          label: "Category"
          value: "blog"
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
